# -*- mode: ruby -*-
# vi: set ft=ruby :

# Instalando o mysql-server (com SCRIPT)
$script_mysql = <<-SCRIPT
apt-get update && \
apt-get install -y mysql-server && \
mysql -e "create user 'phpuser'@'%' identified by 'pass';"
SCRIPT

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  
  ######################################
  #    Defining Multiple Machines      #
  ######################################

  config.vm.define "mysql" do |mysql|
    #####################
    #     Networks      #
    #####################
    # Forwarded Ports
    mysql.vm.network "forwarded_port", guest: 80, host: 8089 
    # Private Networks
      # Static IP
    # mysql.vm.network "private_network", ip: "192.168.56.10"
      # DHCP
    # mysql.vm.network "private_network", type: "dhcp"
    
    # Public Networks
    # mysql.vm.network "public_network"
      # DHCP Assigned Default Route
    # mysql.vm.network "public_network",
    #   use_dhcp_assigned_default_route: true
      # Static IP
    mysql.vm.network "public_network", ip: "192.168.1.17", bridge: "enp0s31f6"

    #########################
    #     provisioning      #
    #########################
    # Shell - Inline Scripts
    # Adicionado chave prublica no "authorized_keys"
    mysql.vm.provision "shell",
      inline: "cat /configs/id_focal64.pub >> .ssh/authorized_keys"
    

    # Instalando o mysql-server (com SCRIPT)
    mysql.vm.provision "shell", inline: $script_mysql
    # Adicionando novas configurações no MySQL
    mysql.vm.provision "shell",
      inline: "cat /configs/mysqld.cnf > /etc/mysql/mysql.conf.d/mysqld.cnf"
    # Reiniciando o MySQL
    mysql.vm.provision "shell", inline: "service mysql restart"

    ###########################
    #     Synced Folders      #
    ###########################
    mysql.vm.synced_folder "./configs", "/configs"
    mysql.vm.synced_folder ".", "/vagrant", disabled: true
  end

  config.vm.define "phpweb" do |phpweb|
    #####################
    #     Networks      #
    #####################
    # Static IP
    phpweb.vm.network "forwarded_port", guest: 8888, host: 8888
    # Forwarded Ports
    phpweb.vm.network "public_network", ip: "192.168.1.18", bridge: "enp0s31f6"

    #########################
    #     provisioning      #
    #########################
    # Adicionado chave prublica no "authorized_keys"
    phpweb.vm.provision "shell",
      inline: "cat /configs/id_focal64.pub >> .ssh/authorized_keys"

    # # Instalando o puppet (com SCRIPT)
    phpweb.vm.provision "shell",
      inline: "apt-get update && apt-get install -y puppet"
    
    ###########################
    #     Synced Folders      #
    ###########################
    # Enable
    phpweb.vm.synced_folder "./configs", "/configs"

    phpweb.vm.provision "puppet" do |puppet|
      puppet.manifests_path = "./configs/manifests"
      puppet.manifest_file = "phpweb.pp"
    end
  end

end
